[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    # '''\/example.*\.pem$''',
                
    # Ignore anything with the word funkymonkey anywhere in the path
    # '''funkymonkey''',

    # sanitize.bats contains an asymmetric Private Key,
    # used as a sample data not actually a secret.
    '''tests\/sanitize.bats$''',
  ]
        
  # Ignore based on any subset of the line
  #regexes = [
  #  # Ignore lines containing pickles
  #  '''pickles''',
  #]
