apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhdh-must-gather

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - pvc.yaml
  - job.yaml
  - data-retriever-pod.yaml

labels:
  - pairs:
      app.kubernetes.io/name: rhdh-must-gather
      app.kubernetes.io/component: diagnostics

images:
  - name: quay.io/rhdh-community/rhdh-must-gather
    newTag: next

