apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhdh-must-gather
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["apps", "extensions"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["rhdh.redhat.com"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["operators.coreos.com"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-must-gather
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-must-gather
subjects:
- kind: ServiceAccount
  name: rhdh-must-gather-sa
  namespace: rhdh-must-gather
