apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdh-must-gather
  namespace: ${NS}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhdh-must-gather
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["apps", "extensions"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["rhdh.redhat.com"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["operators.coreos.com"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-must-gather
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-must-gather
subjects:
- kind: ServiceAccount
  name: rhdh-must-gather
  namespace: ${NS}
---

apiVersion: batch/v1
kind: Job
metadata:
  name: rhdh-must-gather-${JOB_ID}
  namespace: ${NS}
spec:
  activeDeadlineSeconds: 3600
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: rhdh-must-gather
      restartPolicy: Never
      containers:
      - name: gather
        image: ${FULL_IMAGE_NAME}
        args: ${ARGS}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BASE_COLLECTION_PATH
          value: "/must-gather"
        - name: LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: output
          mountPath: /must-gather
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: output
        emptyDir: {}